# This file is automatically generated from traits.build
# package, via the file remake.yml.whisker:
# edit the file there (or the files that it includes).

# Load R resources
library(traits.build)

# Load data resources
schema <- get_schema()
resource_metadata <- get_schema("config/metadata.yml", "metadata")
definitions <- get_schema("config/traits.yml", "traits")
unit_conversions <- get_unit_conversions("config/unit_conversions.csv")
taxon_list <- read_csv_char("config/taxon_list.csv")

# Build each source
Clemann_2023_config <- dataset_configure("data/Clemann_2023/metadata.yml", definitions)
Clemann_2023_raw <- dataset_process("data/Clemann_2023/data.csv", Clemann_2023_config, schema, resource_metadata, unit_conversions)
Clemann_2023 <- dataset_update_taxonomy(Clemann_2023_raw, taxon_list)

Cunningham_2024_config <- dataset_configure("data/Cunningham_2024/metadata.yml", definitions)
Cunningham_2024_raw <- dataset_process("data/Cunningham_2024/data.csv", Cunningham_2024_config, schema, resource_metadata, unit_conversions)
Cunningham_2024 <- dataset_update_taxonomy(Cunningham_2024_raw, taxon_list)

Meiri_2024_config <- dataset_configure("data/Meiri_2024/metadata.yml", definitions)
Meiri_2024_raw <- dataset_process("data/Meiri_2024/data.csv", Meiri_2024_config, schema, resource_metadata, unit_conversions)
Meiri_2024 <- dataset_update_taxonomy(Meiri_2024_raw, taxon_list)

Myhrvold_2015_config <- dataset_configure("data/Myhrvold_2015/metadata.yml", definitions)
Myhrvold_2015_raw <- dataset_process("data/Myhrvold_2015/data.csv", Myhrvold_2015_config, schema, resource_metadata, unit_conversions)
Myhrvold_2015 <- dataset_update_taxonomy(Myhrvold_2015_raw, taxon_list)

Oliveira_2017_config <- dataset_configure("data/Oliveira_2017/metadata.yml", definitions)
Oliveira_2017_raw <- dataset_process("data/Oliveira_2017/data.csv", Oliveira_2017_config, schema, resource_metadata, unit_conversions)
Oliveira_2017 <- dataset_update_taxonomy(Oliveira_2017_raw, taxon_list)

Oskyrko_2024_config <- dataset_configure("data/Oskyrko_2024/metadata.yml", definitions)
Oskyrko_2024_raw <- dataset_process("data/Oskyrko_2024/data.csv", Oskyrko_2024_config, schema, resource_metadata, unit_conversions)
Oskyrko_2024 <- dataset_update_taxonomy(Oskyrko_2024_raw, taxon_list)

Robertson_2019_config <- dataset_configure("data/Robertson_2019/metadata.yml", definitions)
Robertson_2019_raw <- dataset_process("data/Robertson_2019/data.csv", Robertson_2019_config, schema, resource_metadata, unit_conversions)
Robertson_2019 <- dataset_update_taxonomy(Robertson_2019_raw, taxon_list)

Soria_2021_config <- dataset_configure("data/Soria_2021/metadata.yml", definitions)
Soria_2021_raw <- dataset_process("data/Soria_2021/data.csv", Soria_2021_config, schema, resource_metadata, unit_conversions)
Soria_2021 <- dataset_update_taxonomy(Soria_2021_raw, taxon_list)

Tobias_2022_config <- dataset_configure("data/Tobias_2022/metadata.yml", definitions)
Tobias_2022_raw <- dataset_process("data/Tobias_2022/data.csv", Tobias_2022_config, schema, resource_metadata, unit_conversions)
Tobias_2022 <- dataset_update_taxonomy(Tobias_2022_raw, taxon_list)

Wilman_2014_config <- dataset_configure("data/Wilman_2014/metadata.yml", definitions)
Wilman_2014_raw <- dataset_process("data/Wilman_2014/data.csv", Wilman_2014_config, schema, resource_metadata, unit_conversions)
Wilman_2014 <- dataset_update_taxonomy(Wilman_2014_raw, taxon_list)

Wilman_2016_config <- dataset_configure("data/Wilman_2016/metadata.yml", definitions)
Wilman_2016_raw <- dataset_process("data/Wilman_2016/data.csv", Wilman_2016_config, schema, resource_metadata, unit_conversions)
Wilman_2016 <- dataset_update_taxonomy(Wilman_2016_raw, taxon_list)


traits.build_database_CH_raw <- austraits::bind_databases(
  Clemann_2023,
  Cunningham_2024,
  Meiri_2024,
  Myhrvold_2015,
  Oliveira_2017,
  Oskyrko_2024,
  Robertson_2019,
  Soria_2021,
  Tobias_2022,
  Wilman_2014,
  Wilman_2016,
  NULL)

# Version information
version_number <- util_get_version("config/metadata.yml")
git_SHA <- util_get_SHA()

# Combine all the source into one resource
traits.build_database_CH <- build_add_version(traits.build_database_CH_raw, version_number, git_SHA)

# Save to file
dir.create("export/data/curr", FALSE, TRUE)
saveRDS(traits.build_database_CH, "export/data/curr/traits.build_database_CH.rds")
